Namespace for global variables

diff --git a/nest-in b/nest-in
--- a/nest-in
+++ b/nest-in
@@ -3,19 +3,19 @@
 #
 # Essentials
 
-SCRIPT_NAME=$(basename $0)
+NEST_IN__SCRIPT_NAME=nest-in
 
-TS_N='\e[0m'
-TS_B='\e[1m'
-TS_U='\e[4m'
+NEST_IN__TS_N='\e[0m'
+NEST_IN__TS_B='\e[1m'
+NEST_IN__TS_U='\e[4m'
 TS_ERROR='\e[0;31m'
 
-ERROR_STYLE_BEGIN=''
-ERROR_STYLE_END=''
+NEST_IN__TS_ERR=''
+NEST_IN__TS_ERR_END=''
 if [ -t 1 ] && [ $(tput colors) \> 0 ]
 then
-	ERROR_STYLE_BEGIN="$TS_ERROR"
-	ERROR_STYLE_END="$TS_N"
+	NEST_IN__TS_ERR="$TS_ERROR"
+	NEST_IN__TS_ERR_END="$NEST_IN__TS_N"
 fi
 
 printf-stderr()
@@ -25,7 +25,7 @@ printf-stderr()
 
 printf-error()
 {
-	printf-stderr "$ERROR_STYLE_BEGIN$SCRIPT_NAME error:$ERROR_STYLE_END "
+	printf-stderr "$NEST_IN__TS_ERR$NEST_IN__SCRIPT_NAME error:$NEST_IN__TS_ERR_END "
 	printf-stderr "$@"
 	printf-stderr '\n'
 }
@@ -38,46 +38,48 @@ printf-message()
 
 printf-nest-in-message()
 {
-	printf-stderr "${TS_U}$SCRIPT_NAME${TS_N}: "
+	printf-stderr "${NEST_IN__TS_U}$NEST_IN__SCRIPT_NAME${NEST_IN__TS_N}: "
 	printf-stderr "$@"
 	printf-stderr '\n'
+}
+
+print-help()
+{
+	printf \
+"${NEST_IN__TS_B}USAGE${NEST_IN__TS_N}
+  ${NEST_IN__TS_B}nest-in${NEST_IN__TS_N} [${NEST_IN__TS_U}-dsr${NEST_IN__TS_N}] [${NEST_IN__TS_U}targets...${NEST_IN__TS_N}] [${NEST_IN__TS_U}-k${NEST_IN__TS_N}] -- [${NEST_IN__TS_U}file${NEST_IN__TS_N}]
+
+${NEST_IN__TS_B}OPTIONS${NEST_IN__TS_N}
+  [${NEST_IN__TS_U}targets${NEST_IN__TS_N}...]  Specify targets to work with.
+  ${NEST_IN__TS_B}-d${NEST_IN__TS_N}            Show dependencies for targets.
+  ${NEST_IN__TS_B}-s${NEST_IN__TS_N}            Show scenarios for targets.
+  ${NEST_IN__TS_B}--${NEST_IN__TS_N} ${NEST_IN__TS_U}file${NEST_IN__TS_N}       Read nesting info from ${NEST_IN__TS_U}file${NEST_IN__TS_N}.
+  ${NEST_IN__TS_B}--${NEST_IN__TS_N}            Read nesting info from from ${NEST_IN__TS_U}stdin${NEST_IN__TS_N}.
+  ${NEST_IN__TS_B}-h${NEST_IN__TS_N}            Show this message.
+
+${NEST_IN__TS_B}More information at${NEST_IN__TS_N} ${NEST_IN__TS_U}https://github.com/shrpnsld/nest-in${NEST_IN__TS_N}
+"
 }
 
 #
 # Constants
 
-CONFIG_DIR_PATH="$HOME/.config/$SCRIPT_NAME"
-CONFIG_FILE_NAME='twigs.txt'
-DEFAULT_INPUT_FILE_PATH="$CONFIG_DIR_PATH/$CONFIG_FILE_NAME"
-
-HELP_MESSAGE=\
-"${TS_B}USAGE${TS_N}
-  ${TS_B}nest-in${TS_N} [${TS_U}-dsr${TS_N}] [${TS_U}targets...${TS_N}] [${TS_U}-k${TS_N}] -- [${TS_U}file${TS_N}]
-
-${TS_B}OPTIONS${TS_N}
-  [${TS_U}targets${TS_N}...]  Specify targets to work with.
-  ${TS_B}-d${TS_N}            Show dependencies for targets.
-  ${TS_B}-s${TS_N}            Show scenarios for targets.
-  ${TS_B}--${TS_N} ${TS_U}file${TS_N}       Read nesting info from ${TS_U}file${TS_N}.
-  ${TS_B}--${TS_N}            Read nesting info from from ${TS_U}stdin${TS_N}.
-  ${TS_B}-h${TS_N}            Show this message.
-
-${TS_B}More information at${TS_N} ${TS_U}https://github.com/shrpnsld/nest-in${TS_N}
-"
+NEST_IN__CONFIG_DIR_PATH="$HOME/.config/$NEST_IN__SCRIPT_NAME"
+NEST_IN__CONFIG_FILE_NAME='twigs.txt'
+NEST_IN__DEFAULT_TWIGS_PATH="$NEST_IN__CONFIG_DIR_PATH/$NEST_IN__CONFIG_FILE_NAME"
 
 #
 # Options
 
-INPUT_FILE_PATH=''
-INPUT_DESRIPTOR=-1
-INPUT_TARGETS=()
-DO_THE_WORK=:
+NEST_IN__TWIGS_PATH=''
+NEST_IN__TWIGS_DESCRIPTOR=-1
+NEST_IN__INPUT_TARGETS=()
+NEST_IN__DELIMITER_PASSED=false
 
-DELIMITER_PASSED=false
-
+NEST_IN__DO_THE_WORK=:
 do-the-work()
 {
-	"$DO_THE_WORK" "$@"
+	"$NEST_IN__DO_THE_WORK" "$@"
 }
 
 #
@@ -120,15 +122,15 @@ parse-option()
 
 	case "$option" in
 		d)
-			DO_THE_WORK=show-dependencies
+			NEST_IN__DO_THE_WORK=show-dependencies
 			;;
 
 		s)
-			DO_THE_WORK=show-scenarios
+			NEST_IN__DO_THE_WORK=show-scenarios
 			;;
 
 		h)
-			printf "$HELP_MESSAGE"
+			print-help
 			exit
 			;;
 
@@ -175,13 +177,13 @@ parse-arguments()
 				;;
 
 			$PARAMETER_TYPE_TARGET)
-				INPUT_TARGETS+=("$parameter")
+				NEST_IN__INPUT_TARGETS+=("$parameter")
 				;;
 
 			$PARAMETER_TYPE_DELIMITER)
 				(( ++parameter_index ))
-				DELIMITER_PASSED=true
-				INPUT_FILE_PATH="${parameters[$parameter_index]}"
+				NEST_IN__DELIMITER_PASSED=true
+				NEST_IN__TWIGS_PATH="${parameters[$parameter_index]}"
 				break
 				;;
 
@@ -195,27 +197,27 @@ parse-arguments()
 
 validate-options()
 {
-	if [ -n "$INPUT_FILE_PATH" ]
+	if [ -n "$NEST_IN__TWIGS_PATH" ]
 	then
-		exec 3< "$INPUT_FILE_PATH"
-		INPUT_DESCRIPTOR=3
-	elif $DELIMITER_PASSED
+		exec 3< "$NEST_IN__TWIGS_PATH"
+		NEST_IN__TWIGS_DESCRIPTOR=3
+	elif $NEST_IN__DELIMITER_PASSED
 	then
-		INPUT_DESCRIPTOR=0
+		NEST_IN__TWIGS_DESCRIPTOR=0
 	else
-		if ! [ -r "$DEFAULT_INPUT_FILE_PATH" ]
+		if ! [ -r "$NEST_IN__DEFAULT_TWIGS_PATH" ]
 		then
-			printf-error 'failed to open config file "%s"' "$DEFAULT_INPUT_FILE_PATH"
+			printf-error 'failed to open config file "%s"' "$NEST_IN__DEFAULT_TWIGS_PATH"
 			exit 1
 		fi
 
-		exec 3< "$DEFAULT_INPUT_FILE_PATH"
-		INPUT_DESCRIPTOR=3
+		exec 3< "$NEST_IN__DEFAULT_TWIGS_PATH"
+		NEST_IN__TWIGS_DESCRIPTOR=3
 	fi
 
-	if [ "$DO_THE_WORK" == : ]
+	if [ "$NEST_IN__DO_THE_WORK" == : ]
 	then
-		DO_THE_WORK=start-nesting
+		NEST_IN__DO_THE_WORK=start-nesting
 	fi
 }
 
@@ -373,7 +375,7 @@ read-target-declaration()
 	local dependencies=("${READ_DEPENDENCIES_RETURN__DEPENDENCIES[@]}")
 
 	local target_variable_name=$(variable-name-from-target "$target")
-	eval "NEST_DEPENDENCIES_${target_variable_name}=(${dependencies[@]})"
+	eval "NEST_IN__DEPENDENCIES_${target_variable_name}=(${dependencies[@]})"
 
 	READ_TARGET_DECLARATION_RETURN__TARGET="$target"
 }
@@ -434,7 +436,7 @@ gather-twigs()
         
 		local target="$READ_TARGET_DECLARATION_RETURN__TARGET"
 		local variable_name=$(variable-name-from-target "$target")
-		printf -v "NEST_SCENARIO_${variable_name}" '%s' "$READ_TARGET_SCENARIO_RETURN__SCENARIO"
+		printf -v "NEST_IN__SCENARIO_${variable_name}" '%s' "$READ_TARGET_SCENARIO_RETURN__SCENARIO"
 		unmark-target "$target" # basically create information about mark
 	done
 
@@ -464,7 +466,7 @@ dependencies-for-target()
 	local target=$1
 
 	local variable_name=$(variable-name-from-target "$target")
-	eval "DEPENDENCIES_FOR_TARGET_RETURN__DEPENDENCIES=("\${NEST_DEPENDENCIES_${variable_name}[@]}")"
+	eval "DEPENDENCIES_FOR_TARGET_RETURN__DEPENDENCIES=("\${NEST_IN__DEPENDENCIES_${variable_name}[@]}")"
 }
 
 dependencies-for-target-recursive()
@@ -575,7 +577,7 @@ check-input-targets-exist()
 {
 	local gathered_targets=("$@")
 
-	for target in "${INPUT_TARGETS[@]}"
+	for target in "${NEST_IN__INPUT_TARGETS[@]}"
 	do
 		if ! array-contains-item "$target" "${gathered_targets[@]}"
 		then
@@ -591,7 +593,7 @@ scenario-for-target()
 	local target=$1
 
 	local variable_name=$(variable-name-from-target "$target")
-	eval "SCENARIO_FOR_TARGET_RETURN__SCENARIO=(\"\$NEST_SCENARIO_${variable_name}\")"
+	eval "SCENARIO_FOR_TARGET_RETURN__SCENARIO=(\"\$NEST_IN__SCENARIO_${variable_name}\")"
 }
 
 is-target-marked()
@@ -599,7 +601,7 @@ is-target-marked()
 	local target=$1
 
 	local variable_name=$(variable-name-from-target "$target")
-	local target_installed="NESTS_MARKED_${variable_name}"
+	local target_installed="NEST_IN__MARKED_${variable_name}"
 	${!target_installed}
 }
 
@@ -608,7 +610,7 @@ unmark-target()
 	local target=$1
 
 	local variable_name=$(variable-name-from-target "$target")
-	local target_installed="NESTS_MARKED_${variable_name}"
+	local target_installed="NEST_IN__MARKED_${variable_name}"
 	printf -v "$target_installed" false
 }
 
@@ -617,7 +619,7 @@ mark-target()
 	local target=$1
 
 	local variable_name=$(variable-name-from-target "$target")
-	local target_installed="NESTS_MARKED_${variable_name}"
+	local target_installed="NEST_IN__MARKED_${variable_name}"
 	printf -v "$target_installed" true
 }
 
@@ -636,13 +638,13 @@ show-dependencies()
 	local targets=("$@")
 
 	local target="${targets[0]}"
-	printf "${TS_U}%s${TS_N}\n" "$target"
+	printf "${NEST_IN__TS_U}%s${NEST_IN__TS_N}\n" "$target"
 	dependencies-for-target-recursive "$target" | sort | uniq
 
 	for target in "${targets[@]:1}"
 	do
 		printf '\n'
-		printf "${TS_U}%s${TS_N}\n" "$target"
+		printf "${NEST_IN__TS_U}%s${NEST_IN__TS_N}\n" "$target"
 		dependencies-for-target-recursive "$target" | sort | uniq
 	done
 }
@@ -652,7 +654,7 @@ show-scenarios()
 	local targets=("$@")
 
 	local target="${targets[0]}"
-	printf "${TS_U}%s${TS_N}\n" "$target"
+	printf "${NEST_IN__TS_U}%s${NEST_IN__TS_N}\n" "$target"
 
 	scenario-for-target "$target"
 	local scenario="$SCENARIO_FOR_TARGET_RETURN__SCENARIO"
@@ -661,7 +663,7 @@ show-scenarios()
 	for target in "${targets[@]:1}"
 	do
 		printf '\n'
-		printf "${TS_U}%s${TS_N}\n" "$target"
+		printf "${NEST_IN__TS_U}%s${NEST_IN__TS_N}\n" "$target"
 
 		scenario-for-target "$target"
 		local scenario="$SCENARIO_FOR_TARGET_RETURN__SCENARIO"
@@ -720,7 +722,7 @@ start-nesting()
 }
 
 { # Do the work
-	gather-twigs $INPUT_DESCRIPTOR
+	gather-twigs $NEST_IN__TWIGS_DESCRIPTOR
 	gathered_targets=("${GATHER_TWIGS_RETURN__TARGETS[@]}")
 
 	check-all-targets-exist "${gathered_targets[@]}" &&
@@ -731,11 +733,11 @@ start-nesting()
 		exit 1
 	fi
 
-	if [[ ${#INPUT_TARGETS[@]} == 0 ]]
+	if [[ ${#NEST_IN__INPUT_TARGETS[@]} == 0 ]]
 	then
 		targets=("${gathered_targets[@]}")
 	else
-		targets=("${INPUT_TARGETS[@]}")
+		targets=("${NEST_IN__INPUT_TARGETS[@]}")
 	fi
 
 	do-the-work "${targets[@]}"
